# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    env: 
      NAME: test
    
    steps:
    - name: Read Secret Values
      run: echo "My Secret is ${{ secrets.JWT_SECRET }}"
      
    - name: Read Variables Values
      run: echo "My Secret is ${{ vars.JWT_SECRET }}"
      
    - name: Check out repository code
      uses: actions/checkout@v3
      
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: Install Dependencies 
      run: npm ci
      working-directory: ./bookmark-app

    - name: Start services with docker-compose
      working-directory: ./bookmark-app
      run: npm run db:test:restart
    
    - name: Run Project
      run: npm run start:dev
      working-directory: ./bookmark-app
