# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  my-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest  
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432  
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: Install Dependencies 
      run: npm ci
      working-directory: ./bookmark-app

    - name: Run Project
      run: npm run start:dev
      working-directory: ./bookmark-app
